package
{
	import com.thaumaturgistgames.flakit.Library;
	
	/**
	* Generated with LibraryBuilder for FLAKit
	* http://www.thaumaturgistgames.com/FLAKit
	*/
	public class EmbeddedAssets
	{
		[Embed(source = "../lib/arrow.png")] private const FLAKIT_ASSET$_518516027:Class;
		[Embed(source = "../lib/bossBolt.png")] private const FLAKIT_ASSET$118345770:Class;
		[Embed(source = "../lib/caltrop.png")] private const FLAKIT_ASSET$_2023004771:Class;
		[Embed(source = "../lib/creditRoll.png")] private const FLAKIT_ASSET$_1681465106:Class;
		[Embed(source = "../lib/endingScreen.png")] private const FLAKIT_ASSET$1907198727:Class;
		[Embed(source = "../lib/fighter.png")] private const FLAKIT_ASSET$_871594066:Class;
		[Embed(source = "../lib/fireballShot.png")] private const FLAKIT_ASSET$_2085384948:Class;
		[Embed(source = "../lib/iceBlast.png")] private const FLAKIT_ASSET$1153268590:Class;
		[Embed(source = "../lib/lightningBolt.png")] private const FLAKIT_ASSET$193909145:Class;
		[Embed(source = "../lib/mage.png")] private const FLAKIT_ASSET$_424473242:Class;
		[Embed(source = "../lib/rogue.png")] private const FLAKIT_ASSET$200819418:Class;
		[Embed(source = "../lib/shuriken.png")] private const FLAKIT_ASSET$_1550721049:Class;
		[Embed(source = "../lib/smoke.png")] private const FLAKIT_ASSET$1497630657:Class;
		[Embed(source = "../lib/titleScreen.png")] private const FLAKIT_ASSET$1597682957:Class;
		[Embed(source = "../lib/unclassed.png")] private const FLAKIT_ASSET$1800156088:Class;
		[Embed(source = "../lib/vortex.png")] private const FLAKIT_ASSET$_290577958:Class;
		[Embed(source = "../lib/webShot.png")] private const FLAKIT_ASSET$1953257261:Class;
		[Embed(source = "../lib/webTrap.png")] private const FLAKIT_ASSET$1147261799:Class;
		[Embed(source = "../lib/webTrapFighter.png")] private const FLAKIT_ASSET$_1145532067:Class;
		[Embed(source = "../lib/wisp.png")] private const FLAKIT_ASSET$_2098054628:Class;
		[Embed(source = "../lib/tower/bg.png")] private const FLAKIT_ASSET$1725213281:Class;
		[Embed(source = "../lib/tower/platform.png")] private const FLAKIT_ASSET$_1771787809:Class;
		[Embed(source = "../lib/tower/layouts/layout1.png")] private const FLAKIT_ASSET$_1326837725:Class;
		[Embed(source = "../lib/tower/layouts/layout2.png")] private const FLAKIT_ASSET$_1326837758:Class;
		[Embed(source = "../lib/tower/decals/cellDoor.png")] private const FLAKIT_ASSET$_1174255737:Class;
		[Embed(source = "../lib/tower/decals/chandelier.png")] private const FLAKIT_ASSET$_233244515:Class;
		[Embed(source = "../lib/tower/decals/door.png")] private const FLAKIT_ASSET$94821841:Class;
		[Embed(source = "../lib/tower/decals/gate.png")] private const FLAKIT_ASSET$1785658594:Class;
		[Embed(source = "../lib/tower/decals/gateWall.png")] private const FLAKIT_ASSET$_529111937:Class;
		[Embed(source = "../lib/tower/decals/shield.png")] private const FLAKIT_ASSET$1993334970:Class;
		[Embed(source = "../lib/tower/decals/stainedGlass.png")] private const FLAKIT_ASSET$_355665397:Class;
		[Embed(source = "../lib/tower/decals/torch.png")] private const FLAKIT_ASSET$_1813486014:Class;
		[Embed(source = "../lib/tower/decals/window.png")] private const FLAKIT_ASSET$_1300309153:Class;
		[Embed(source = "../lib/misc/arrowDrop.png")] private const FLAKIT_ASSET$1073196703:Class;
		[Embed(source = "../lib/misc/clipPlatform.png")] private const FLAKIT_ASSET$_1443783385:Class;
		[Embed(source = "../lib/misc/dotPlatform.png")] private const FLAKIT_ASSET$399860199:Class;
		[Embed(source = "../lib/misc/doubleRight.png")] private const FLAKIT_ASSET$_969195113:Class;
		[Embed(source = "../lib/misc/enter.png")] private const FLAKIT_ASSET$1447648390:Class;
		[Embed(source = "../lib/misc/healthDrop.png")] private const FLAKIT_ASSET$1092521136:Class;
		[Embed(source = "../lib/misc/keyA.png")] private const FLAKIT_ASSET$_512860663:Class;
		[Embed(source = "../lib/misc/keyD.png")] private const FLAKIT_ASSET$_512861026:Class;
		[Embed(source = "../lib/misc/keyDrop.png")] private const FLAKIT_ASSET$_2111604354:Class;
		[Embed(source = "../lib/misc/keyS.png")] private const FLAKIT_ASSET$_512861193:Class;
		[Embed(source = "../lib/misc/keySpace.png")] private const FLAKIT_ASSET$1365752265:Class;
		[Embed(source = "../lib/misc/ladder.png")] private const FLAKIT_ASSET$_125205688:Class;
		[Embed(source = "../lib/misc/lever.png")] private const FLAKIT_ASSET$_1067856766:Class;
		[Embed(source = "../lib/misc/leverAnimation.png")] private const FLAKIT_ASSET$816539504:Class;
		[Embed(source = "../lib/misc/leverL.png")] private const FLAKIT_ASSET$14545707:Class;
		[Embed(source = "../lib/misc/leverR.png")] private const FLAKIT_ASSET$296870709:Class;
		[Embed(source = "../lib/misc/manaDrop.png")] private const FLAKIT_ASSET$_1503352562:Class;
		[Embed(source = "../lib/misc/padlock.png")] private const FLAKIT_ASSET$1124931390:Class;
		[Embed(source = "../lib/misc/ropeLadder.png")] private const FLAKIT_ASSET$995121159:Class;
		[Embed(source = "../lib/misc/shurikenDrop.png")] private const FLAKIT_ASSET$76353965:Class;
		[Embed(source = "../lib/misc/upArrow.png")] private const FLAKIT_ASSET$539195797:Class;
		[Embed(source = "../lib/icons/arrowIcon.png")] private const FLAKIT_ASSET$_1268700239:Class;
		[Embed(source = "../lib/icons/blinkIcon.png")] private const FLAKIT_ASSET$_860172798:Class;
		[Embed(source = "../lib/icons/caltropIcon.png")] private const FLAKIT_ASSET$1264984618:Class;
		[Embed(source = "../lib/icons/energyIcon.png")] private const FLAKIT_ASSET$_142815401:Class;
		[Embed(source = "../lib/icons/healthIcon.png")] private const FLAKIT_ASSET$536807520:Class;
		[Embed(source = "../lib/icons/keyA.png")] private const FLAKIT_ASSET$287487750:Class;
		[Embed(source = "../lib/icons/keyD.png")] private const FLAKIT_ASSET$297776902:Class;
		[Embed(source = "../lib/icons/keyLR.png")] private const FLAKIT_ASSET$_1886695584:Class;
		[Embed(source = "../lib/icons/keyS.png")] private const FLAKIT_ASSET$308590342:Class;
		[Embed(source = "../lib/icons/keySpace.png")] private const FLAKIT_ASSET$_1665366036:Class;
		[Embed(source = "../lib/icons/keyUD.png")] private const FLAKIT_ASSET$1573420866:Class;
		[Embed(source = "../lib/icons/manaIcon.png")] private const FLAKIT_ASSET$_1670434473:Class;
		[Embed(source = "../lib/icons/shieldIcon.png")] private const FLAKIT_ASSET$_839247721:Class;
		[Embed(source = "../lib/icons/shurikenIcon.png")] private const FLAKIT_ASSET$1783742332:Class;
		[Embed(source = "../lib/HUD/bg.png")] private const FLAKIT_ASSET$737044750:Class;
		[Embed(source = "../lib/HUD/bolt.png")] private const FLAKIT_ASSET$1732831878:Class;
		[Embed(source = "../lib/HUD/bow.png")] private const FLAKIT_ASSET$_1406130890:Class;
		[Embed(source = "../lib/HUD/caltrop.png")] private const FLAKIT_ASSET$1960930795:Class;
		[Embed(source = "../lib/HUD/daggers.png")] private const FLAKIT_ASSET$_1846139305:Class;
		[Embed(source = "../lib/HUD/emptyA.png")] private const FLAKIT_ASSET$445724351:Class;
		[Embed(source = "../lib/HUD/emptyD.png")] private const FLAKIT_ASSET$456013503:Class;
		[Embed(source = "../lib/HUD/emptyS.png")] private const FLAKIT_ASSET$418592447:Class;
		[Embed(source = "../lib/HUD/fire.png")] private const FLAKIT_ASSET$_70592548:Class;
		[Embed(source = "../lib/HUD/ice.png")] private const FLAKIT_ASSET$_1787734091:Class;
		[Embed(source = "../lib/HUD/keyDrop.png")] private const FLAKIT_ASSET$576991500:Class;
		[Embed(source = "../lib/HUD/muted.png")] private const FLAKIT_ASSET$1773495171:Class;
		[Embed(source = "../lib/HUD/shield.png")] private const FLAKIT_ASSET$_1313700221:Class;
		[Embed(source = "../lib/HUD/shuriken.png")] private const FLAKIT_ASSET$804742393:Class;
		[Embed(source = "../lib/HUD/sword.png")] private const FLAKIT_ASSET$24083986:Class;
		[Embed(source = "../lib/HUD/unmuted.png")] private const FLAKIT_ASSET$_2085238864:Class;
		[Embed(source = "../lib/hellther/bg.png")] private const FLAKIT_ASSET$952775083:Class;
		[Embed(source = "../lib/hellther/crevice.png")] private const FLAKIT_ASSET$_1047334745:Class;
		[Embed(source = "../lib/hellther/ladder.png")] private const FLAKIT_ASSET$994623346:Class;
		[Embed(source = "../lib/hellther/lavaTrap.png")] private const FLAKIT_ASSET$1836315230:Class;
		[Embed(source = "../lib/hellther/lavaTrap2.png")] private const FLAKIT_ASSET$1725049871:Class;
		[Embed(source = "../lib/hellther/layout1.png")] private const FLAKIT_ASSET$_687901717:Class;
		[Embed(source = "../lib/hellther/layout2.png")] private const FLAKIT_ASSET$_1089571861:Class;
		[Embed(source = "../lib/hellther/layout3.png")] private const FLAKIT_ASSET$_955681813:Class;
		[Embed(source = "../lib/hellther/layout4.png")] private const FLAKIT_ASSET$171996139:Class;
		[Embed(source = "../lib/hellther/layout5.png")] private const FLAKIT_ASSET$305886187:Class;
		[Embed(source = "../lib/hellther/platform.png")] private const FLAKIT_ASSET$_1891366353:Class;
		[Embed(source = "../lib/hellther/portal.png")] private const FLAKIT_ASSET$_1783677173:Class;
		[Embed(source = "../lib/hellther/portalFrame.png")] private const FLAKIT_ASSET$_1966077773:Class;
		[Embed(source = "../lib/hellther/portalSparks.png")] private const FLAKIT_ASSET$_2097114851:Class;
		[Embed(source = "../lib/forest/archway.png")] private const FLAKIT_ASSET$_612279632:Class;
		[Embed(source = "../lib/forest/forestBG.png")] private const FLAKIT_ASSET$_629779165:Class;
		[Embed(source = "../lib/forest/house.png")] private const FLAKIT_ASSET$1335045195:Class;
		[Embed(source = "../lib/forest/house2.png")] private const FLAKIT_ASSET$1278590022:Class;
		[Embed(source = "../lib/forest/lavaAnimation.png")] private const FLAKIT_ASSET$1231621443:Class;
		[Embed(source = "../lib/forest/leftDoor.png")] private const FLAKIT_ASSET$_710182647:Class;
		[Embed(source = "../lib/forest/platform.png")] private const FLAKIT_ASSET$_895726769:Class;
		[Embed(source = "../lib/forest/rightDoor.png")] private const FLAKIT_ASSET$_480644089:Class;
		[Embed(source = "../lib/forest/ropeBridge.png")] private const FLAKIT_ASSET$_1460216769:Class;
		[Embed(source = "../lib/forest/towerDoor.png")] private const FLAKIT_ASSET$_1213875967:Class;
		[Embed(source = "../lib/forest/decals/pineTree.png")] private const FLAKIT_ASSET$316914079:Class;
		[Embed(source = "../lib/forest/decals/stump.png")] private const FLAKIT_ASSET$_1657714078:Class;
		[Embed(source = "../lib/enemies/archer.png")] private const FLAKIT_ASSET$_1251641895:Class;
		[Embed(source = "../lib/enemies/bear.png")] private const FLAKIT_ASSET$_1811389558:Class;
		[Embed(source = "../lib/enemies/boss.png")] private const FLAKIT_ASSET$_1059533712:Class;
		[Embed(source = "../lib/enemies/demon.png")] private const FLAKIT_ASSET$1903992314:Class;
		[Embed(source = "../lib/enemies/elfMage.png")] private const FLAKIT_ASSET$28606730:Class;
		[Embed(source = "../lib/enemies/fighterDop.png")] private const FLAKIT_ASSET$_1632949578:Class;
		[Embed(source = "../lib/enemies/giant.png")] private const FLAKIT_ASSET$_1579280983:Class;
		[Embed(source = "../lib/enemies/guard.png")] private const FLAKIT_ASSET$_924445735:Class;
		[Embed(source = "../lib/enemies/mageDop.png")] private const FLAKIT_ASSET$201438161:Class;
		[Embed(source = "../lib/enemies/rogueDop.png")] private const FLAKIT_ASSET$478098701:Class;
		[Embed(source = "../lib/enemies/scythe.png")] private const FLAKIT_ASSET$357731548:Class;
		[Embed(source = "../lib/enemies/serpent.png")] private const FLAKIT_ASSET$711283937:Class;
		[Embed(source = "../lib/enemies/skeleton.png")] private const FLAKIT_ASSET$_644484842:Class;
		[Embed(source = "../lib/enemies/skeletonMage.png")] private const FLAKIT_ASSET$_2123834409:Class;
		[Embed(source = "../lib/enemies/spider.png")] private const FLAKIT_ASSET$_2104619363:Class;
		[Embed(source = "../lib/enemies/wolf.png")] private const FLAKIT_ASSET$_1675023862:Class;
		[Embed(source = "../lib/enemies/zombie.png")] private const FLAKIT_ASSET$1235186498:Class;
		[Embed(source = "../lib/enemies/bossDeath/s1.png")] private const FLAKIT_ASSET$101831650:Class;
		[Embed(source = "../lib/enemies/bossDeath/s10.png")] private const FLAKIT_ASSET$_144639212:Class;
		[Embed(source = "../lib/enemies/bossDeath/s11.png")] private const FLAKIT_ASSET$_144639435:Class;
		[Embed(source = "../lib/enemies/bossDeath/s12.png")] private const FLAKIT_ASSET$_144639402:Class;
		[Embed(source = "../lib/enemies/bossDeath/s13.png")] private const FLAKIT_ASSET$_144639385:Class;
		[Embed(source = "../lib/enemies/bossDeath/s14.png")] private const FLAKIT_ASSET$_144639352:Class;
		[Embed(source = "../lib/enemies/bossDeath/s2.png")] private const FLAKIT_ASSET$235721698:Class;
		[Embed(source = "../lib/enemies/bossDeath/s3.png")] private const FLAKIT_ASSET$369611746:Class;
		[Embed(source = "../lib/enemies/bossDeath/s4.png")] private const FLAKIT_ASSET$_1025846302:Class;
		[Embed(source = "../lib/enemies/bossDeath/s5.png")] private const FLAKIT_ASSET$_891956254:Class;
		[Embed(source = "../lib/enemies/bossDeath/s6.png")] private const FLAKIT_ASSET$_758066206:Class;
		[Embed(source = "../lib/enemies/bossDeath/s7.png")] private const FLAKIT_ASSET$_1860447262:Class;
		[Embed(source = "../lib/enemies/bossDeath/s8.png")] private const FLAKIT_ASSET$_1103178782:Class;
		[Embed(source = "../lib/enemies/bossDeath/s9.png")] private const FLAKIT_ASSET$_969288734:Class;
		[Embed(source = "../lib/dungeon/bg.png")] private const FLAKIT_ASSET$_1319924279:Class;
		[Embed(source = "../lib/dungeon/platform.png")] private const FLAKIT_ASSET$_610037691:Class;
		[Embed(source = "../lib/dungeon/decals/cellDoor.png")] private const FLAKIT_ASSET$_642163036:Class;
		[Embed(source = "../lib/dungeon/decals/chandelier.png")] private const FLAKIT_ASSET$_1241710435:Class;
		[Embed(source = "../lib/dungeon/decals/cornerWeb.png")] private const FLAKIT_ASSET$_40946760:Class;
		[Embed(source = "../lib/dungeon/decals/crevice.png")] private const FLAKIT_ASSET$_1618064598:Class;
		[Embed(source = "../lib/dungeon/decals/darkness.png")] private const FLAKIT_ASSET$340311090:Class;
		[Embed(source = "../lib/dungeon/decals/door.png")] private const FLAKIT_ASSET$_689039696:Class;
		[Embed(source = "../lib/dungeon/decals/shield.png")] private const FLAKIT_ASSET$_55392338:Class;
		[Embed(source = "../lib/dungeon/decals/stainedGlass.png")] private const FLAKIT_ASSET$_1055518220:Class;
		[Embed(source = "../lib/dungeon/decals/torch.png")] private const FLAKIT_ASSET$_1005829387:Class;
		[Embed(source = "../lib/dungeon/decals/web1.png")] private const FLAKIT_ASSET$1917177926:Class;
		[Embed(source = "../lib/dungeon/decals/window.png")] private const FLAKIT_ASSET$913944423:Class;
		[Embed(source = "../lib/beach/bg.png")] private const FLAKIT_ASSET$_1016859385:Class;
		[Embed(source = "../lib/beach/bg2.png")] private const FLAKIT_ASSET$_2022735386:Class;
		[Embed(source = "../lib/beach/crate.png")] private const FLAKIT_ASSET$_432456929:Class;
		[Embed(source = "../lib/beach/dynamicDebris.png")] private const FLAKIT_ASSET$_172551549:Class;
		[Embed(source = "../lib/beach/lightningBolt.png")] private const FLAKIT_ASSET$_208024148:Class;
		[Embed(source = "../lib/beach/shipAnimation.png")] private const FLAKIT_ASSET$1524607723:Class;
		[Embed(source = "../lib/beach/towerLightning.png")] private const FLAKIT_ASSET$1413686369:Class;
		[Embed(source = "../lib/beach/waterDebris.png")] private const FLAKIT_ASSET$_1041424489:Class;
		[Embed(source = "../lib/beach/waterDebris2.png")] private const FLAKIT_ASSET$_1921118310:Class;
		[Embed(source = "../lib/balcony/bg.png")] private const FLAKIT_ASSET$_1952964103:Class;
		[Embed(source = "../lib/balcony/distantShip.png")] private const FLAKIT_ASSET$1132726687:Class;
		[Embed(source = "../lib/balcony/platform.png")] private const FLAKIT_ASSET$903879535:Class;
		[Embed(source = "../lib/audio/sfx/beachAmbiance.mp3")] private const FLAKIT_ASSET$_1721183005:Class;
		[Embed(source = "../lib/audio/sfx/bearAttack.mp3")] private const FLAKIT_ASSET$_1048980777:Class;
		[Embed(source = "../lib/audio/sfx/bigDoorOpen.mp3")] private const FLAKIT_ASSET$1013157834:Class;
		[Embed(source = "../lib/audio/sfx/blink.mp3")] private const FLAKIT_ASSET$1568168097:Class;
		[Embed(source = "../lib/audio/sfx/bolt.mp3")] private const FLAKIT_ASSET$898355145:Class;
		[Embed(source = "../lib/audio/sfx/bow.mp3")] private const FLAKIT_ASSET$_1081717828:Class;
		[Embed(source = "../lib/audio/sfx/daggerStab.mp3")] private const FLAKIT_ASSET$2114795605:Class;
		[Embed(source = "../lib/audio/sfx/demon.mp3")] private const FLAKIT_ASSET$_1273588036:Class;
		[Embed(source = "../lib/audio/sfx/demonDie.mp3")] private const FLAKIT_ASSET$_1325507663:Class;
		[Embed(source = "../lib/audio/sfx/fireball.mp3")] private const FLAKIT_ASSET$839206465:Class;
		[Embed(source = "../lib/audio/sfx/frostAttack.mp3")] private const FLAKIT_ASSET$_1377963815:Class;
		[Embed(source = "../lib/audio/sfx/keys.mp3")] private const FLAKIT_ASSET$_714000285:Class;
		[Embed(source = "../lib/audio/sfx/pickup.mp3")] private const FLAKIT_ASSET$_522000301:Class;
		[Embed(source = "../lib/audio/sfx/serpentHiss.mp3")] private const FLAKIT_ASSET$_665961522:Class;
		[Embed(source = "../lib/audio/sfx/skeletonDie.mp3")] private const FLAKIT_ASSET$_1703239848:Class;
		[Embed(source = "../lib/audio/sfx/smallDoorOpen.mp3")] private const FLAKIT_ASSET$_924790506:Class;
		[Embed(source = "../lib/audio/sfx/spiderHiss.mp3")] private const FLAKIT_ASSET$_183583457:Class;
		[Embed(source = "../lib/audio/sfx/startToBeach.mp3")] private const FLAKIT_ASSET$421538717:Class;
		[Embed(source = "../lib/audio/sfx/swordSlash.mp3")] private const FLAKIT_ASSET$_1664806651:Class;
		[Embed(source = "../lib/audio/sfx/throw.mp3")] private const FLAKIT_ASSET$862695400:Class;
		[Embed(source = "../lib/audio/sfx/titleScreenAmbiance.mp3")] private const FLAKIT_ASSET$_1269023392:Class;
		[Embed(source = "../lib/audio/sfx/unlock.mp3")] private const FLAKIT_ASSET$_1381489883:Class;
		[Embed(source = "../lib/audio/sfx/Wisp.mp3")] private const FLAKIT_ASSET$_1864778843:Class;
		[Embed(source = "../lib/audio/sfx/wolfAttack.mp3")] private const FLAKIT_ASSET$526945885:Class;
		[Embed(source = "../lib/audio/sfx/zombieAttack.mp3")] private const FLAKIT_ASSET$133286864:Class;
		[Embed(source = "../lib/audio/sfx/zombieDie.mp3")] private const FLAKIT_ASSET$_300141609:Class;
		[Embed(source = "../lib/audio/music/beach.mp3")] private const FLAKIT_ASSET$1479672229:Class;
		[Embed(source = "../lib/audio/music/boss.mp3")] private const FLAKIT_ASSET$2072822914:Class;
		[Embed(source = "../lib/audio/music/dungeon.mp3")] private const FLAKIT_ASSET$1561877272:Class;
		[Embed(source = "../lib/audio/music/finale.mp3")] private const FLAKIT_ASSET$1847966292:Class;
		[Embed(source = "../lib/audio/music/forest.mp3")] private const FLAKIT_ASSET$_1979622991:Class;
		[Embed(source = "../lib/audio/music/hellther.mp3")] private const FLAKIT_ASSET$_713579553:Class;
		[Embed(source = "../lib/audio/music/tower.mp3")] private const FLAKIT_ASSET$_95992901:Class;
		
		public function EmbeddedAssets()
		{
			Library.addImage(String("arrow.png").split("/").join("."), new FLAKIT_ASSET$_518516027);
			Library.addImage(String("bossBolt.png").split("/").join("."), new FLAKIT_ASSET$118345770);
			Library.addImage(String("caltrop.png").split("/").join("."), new FLAKIT_ASSET$_2023004771);
			Library.addImage(String("creditRoll.png").split("/").join("."), new FLAKIT_ASSET$_1681465106);
			Library.addImage(String("endingScreen.png").split("/").join("."), new FLAKIT_ASSET$1907198727);
			Library.addImage(String("fighter.png").split("/").join("."), new FLAKIT_ASSET$_871594066);
			Library.addImage(String("fireballShot.png").split("/").join("."), new FLAKIT_ASSET$_2085384948);
			Library.addImage(String("iceBlast.png").split("/").join("."), new FLAKIT_ASSET$1153268590);
			Library.addImage(String("lightningBolt.png").split("/").join("."), new FLAKIT_ASSET$193909145);
			Library.addImage(String("mage.png").split("/").join("."), new FLAKIT_ASSET$_424473242);
			Library.addImage(String("rogue.png").split("/").join("."), new FLAKIT_ASSET$200819418);
			Library.addImage(String("shuriken.png").split("/").join("."), new FLAKIT_ASSET$_1550721049);
			Library.addImage(String("smoke.png").split("/").join("."), new FLAKIT_ASSET$1497630657);
			Library.addImage(String("titleScreen.png").split("/").join("."), new FLAKIT_ASSET$1597682957);
			Library.addImage(String("unclassed.png").split("/").join("."), new FLAKIT_ASSET$1800156088);
			Library.addImage(String("vortex.png").split("/").join("."), new FLAKIT_ASSET$_290577958);
			Library.addImage(String("webShot.png").split("/").join("."), new FLAKIT_ASSET$1953257261);
			Library.addImage(String("webTrap.png").split("/").join("."), new FLAKIT_ASSET$1147261799);
			Library.addImage(String("webTrapFighter.png").split("/").join("."), new FLAKIT_ASSET$_1145532067);
			Library.addImage(String("wisp.png").split("/").join("."), new FLAKIT_ASSET$_2098054628);
			Library.addImage(String("tower/bg.png").split("/").join("."), new FLAKIT_ASSET$1725213281);
			Library.addImage(String("tower/platform.png").split("/").join("."), new FLAKIT_ASSET$_1771787809);
			Library.addImage(String("tower/layouts/layout1.png").split("/").join("."), new FLAKIT_ASSET$_1326837725);
			Library.addImage(String("tower/layouts/layout2.png").split("/").join("."), new FLAKIT_ASSET$_1326837758);
			Library.addImage(String("tower/decals/cellDoor.png").split("/").join("."), new FLAKIT_ASSET$_1174255737);
			Library.addImage(String("tower/decals/chandelier.png").split("/").join("."), new FLAKIT_ASSET$_233244515);
			Library.addImage(String("tower/decals/door.png").split("/").join("."), new FLAKIT_ASSET$94821841);
			Library.addImage(String("tower/decals/gate.png").split("/").join("."), new FLAKIT_ASSET$1785658594);
			Library.addImage(String("tower/decals/gateWall.png").split("/").join("."), new FLAKIT_ASSET$_529111937);
			Library.addImage(String("tower/decals/shield.png").split("/").join("."), new FLAKIT_ASSET$1993334970);
			Library.addImage(String("tower/decals/stainedGlass.png").split("/").join("."), new FLAKIT_ASSET$_355665397);
			Library.addImage(String("tower/decals/torch.png").split("/").join("."), new FLAKIT_ASSET$_1813486014);
			Library.addImage(String("tower/decals/window.png").split("/").join("."), new FLAKIT_ASSET$_1300309153);
			Library.addImage(String("misc/arrowDrop.png").split("/").join("."), new FLAKIT_ASSET$1073196703);
			Library.addImage(String("misc/clipPlatform.png").split("/").join("."), new FLAKIT_ASSET$_1443783385);
			Library.addImage(String("misc/dotPlatform.png").split("/").join("."), new FLAKIT_ASSET$399860199);
			Library.addImage(String("misc/doubleRight.png").split("/").join("."), new FLAKIT_ASSET$_969195113);
			Library.addImage(String("misc/enter.png").split("/").join("."), new FLAKIT_ASSET$1447648390);
			Library.addImage(String("misc/healthDrop.png").split("/").join("."), new FLAKIT_ASSET$1092521136);
			Library.addImage(String("misc/keyA.png").split("/").join("."), new FLAKIT_ASSET$_512860663);
			Library.addImage(String("misc/keyD.png").split("/").join("."), new FLAKIT_ASSET$_512861026);
			Library.addImage(String("misc/keyDrop.png").split("/").join("."), new FLAKIT_ASSET$_2111604354);
			Library.addImage(String("misc/keyS.png").split("/").join("."), new FLAKIT_ASSET$_512861193);
			Library.addImage(String("misc/keySpace.png").split("/").join("."), new FLAKIT_ASSET$1365752265);
			Library.addImage(String("misc/ladder.png").split("/").join("."), new FLAKIT_ASSET$_125205688);
			Library.addImage(String("misc/lever.png").split("/").join("."), new FLAKIT_ASSET$_1067856766);
			Library.addImage(String("misc/leverAnimation.png").split("/").join("."), new FLAKIT_ASSET$816539504);
			Library.addImage(String("misc/leverL.png").split("/").join("."), new FLAKIT_ASSET$14545707);
			Library.addImage(String("misc/leverR.png").split("/").join("."), new FLAKIT_ASSET$296870709);
			Library.addImage(String("misc/manaDrop.png").split("/").join("."), new FLAKIT_ASSET$_1503352562);
			Library.addImage(String("misc/padlock.png").split("/").join("."), new FLAKIT_ASSET$1124931390);
			Library.addImage(String("misc/ropeLadder.png").split("/").join("."), new FLAKIT_ASSET$995121159);
			Library.addImage(String("misc/shurikenDrop.png").split("/").join("."), new FLAKIT_ASSET$76353965);
			Library.addImage(String("misc/upArrow.png").split("/").join("."), new FLAKIT_ASSET$539195797);
			Library.addImage(String("icons/arrowIcon.png").split("/").join("."), new FLAKIT_ASSET$_1268700239);
			Library.addImage(String("icons/blinkIcon.png").split("/").join("."), new FLAKIT_ASSET$_860172798);
			Library.addImage(String("icons/caltropIcon.png").split("/").join("."), new FLAKIT_ASSET$1264984618);
			Library.addImage(String("icons/energyIcon.png").split("/").join("."), new FLAKIT_ASSET$_142815401);
			Library.addImage(String("icons/healthIcon.png").split("/").join("."), new FLAKIT_ASSET$536807520);
			Library.addImage(String("icons/keyA.png").split("/").join("."), new FLAKIT_ASSET$287487750);
			Library.addImage(String("icons/keyD.png").split("/").join("."), new FLAKIT_ASSET$297776902);
			Library.addImage(String("icons/keyLR.png").split("/").join("."), new FLAKIT_ASSET$_1886695584);
			Library.addImage(String("icons/keyS.png").split("/").join("."), new FLAKIT_ASSET$308590342);
			Library.addImage(String("icons/keySpace.png").split("/").join("."), new FLAKIT_ASSET$_1665366036);
			Library.addImage(String("icons/keyUD.png").split("/").join("."), new FLAKIT_ASSET$1573420866);
			Library.addImage(String("icons/manaIcon.png").split("/").join("."), new FLAKIT_ASSET$_1670434473);
			Library.addImage(String("icons/shieldIcon.png").split("/").join("."), new FLAKIT_ASSET$_839247721);
			Library.addImage(String("icons/shurikenIcon.png").split("/").join("."), new FLAKIT_ASSET$1783742332);
			Library.addImage(String("HUD/bg.png").split("/").join("."), new FLAKIT_ASSET$737044750);
			Library.addImage(String("HUD/bolt.png").split("/").join("."), new FLAKIT_ASSET$1732831878);
			Library.addImage(String("HUD/bow.png").split("/").join("."), new FLAKIT_ASSET$_1406130890);
			Library.addImage(String("HUD/caltrop.png").split("/").join("."), new FLAKIT_ASSET$1960930795);
			Library.addImage(String("HUD/daggers.png").split("/").join("."), new FLAKIT_ASSET$_1846139305);
			Library.addImage(String("HUD/emptyA.png").split("/").join("."), new FLAKIT_ASSET$445724351);
			Library.addImage(String("HUD/emptyD.png").split("/").join("."), new FLAKIT_ASSET$456013503);
			Library.addImage(String("HUD/emptyS.png").split("/").join("."), new FLAKIT_ASSET$418592447);
			Library.addImage(String("HUD/fire.png").split("/").join("."), new FLAKIT_ASSET$_70592548);
			Library.addImage(String("HUD/ice.png").split("/").join("."), new FLAKIT_ASSET$_1787734091);
			Library.addImage(String("HUD/keyDrop.png").split("/").join("."), new FLAKIT_ASSET$576991500);
			Library.addImage(String("HUD/muted.png").split("/").join("."), new FLAKIT_ASSET$1773495171);
			Library.addImage(String("HUD/shield.png").split("/").join("."), new FLAKIT_ASSET$_1313700221);
			Library.addImage(String("HUD/shuriken.png").split("/").join("."), new FLAKIT_ASSET$804742393);
			Library.addImage(String("HUD/sword.png").split("/").join("."), new FLAKIT_ASSET$24083986);
			Library.addImage(String("HUD/unmuted.png").split("/").join("."), new FLAKIT_ASSET$_2085238864);
			Library.addImage(String("hellther/bg.png").split("/").join("."), new FLAKIT_ASSET$952775083);
			Library.addImage(String("hellther/crevice.png").split("/").join("."), new FLAKIT_ASSET$_1047334745);
			Library.addImage(String("hellther/ladder.png").split("/").join("."), new FLAKIT_ASSET$994623346);
			Library.addImage(String("hellther/lavaTrap.png").split("/").join("."), new FLAKIT_ASSET$1836315230);
			Library.addImage(String("hellther/lavaTrap2.png").split("/").join("."), new FLAKIT_ASSET$1725049871);
			Library.addImage(String("hellther/layout1.png").split("/").join("."), new FLAKIT_ASSET$_687901717);
			Library.addImage(String("hellther/layout2.png").split("/").join("."), new FLAKIT_ASSET$_1089571861);
			Library.addImage(String("hellther/layout3.png").split("/").join("."), new FLAKIT_ASSET$_955681813);
			Library.addImage(String("hellther/layout4.png").split("/").join("."), new FLAKIT_ASSET$171996139);
			Library.addImage(String("hellther/layout5.png").split("/").join("."), new FLAKIT_ASSET$305886187);
			Library.addImage(String("hellther/platform.png").split("/").join("."), new FLAKIT_ASSET$_1891366353);
			Library.addImage(String("hellther/portal.png").split("/").join("."), new FLAKIT_ASSET$_1783677173);
			Library.addImage(String("hellther/portalFrame.png").split("/").join("."), new FLAKIT_ASSET$_1966077773);
			Library.addImage(String("hellther/portalSparks.png").split("/").join("."), new FLAKIT_ASSET$_2097114851);
			Library.addImage(String("forest/archway.png").split("/").join("."), new FLAKIT_ASSET$_612279632);
			Library.addImage(String("forest/forestBG.png").split("/").join("."), new FLAKIT_ASSET$_629779165);
			Library.addImage(String("forest/house.png").split("/").join("."), new FLAKIT_ASSET$1335045195);
			Library.addImage(String("forest/house2.png").split("/").join("."), new FLAKIT_ASSET$1278590022);
			Library.addImage(String("forest/lavaAnimation.png").split("/").join("."), new FLAKIT_ASSET$1231621443);
			Library.addImage(String("forest/leftDoor.png").split("/").join("."), new FLAKIT_ASSET$_710182647);
			Library.addImage(String("forest/platform.png").split("/").join("."), new FLAKIT_ASSET$_895726769);
			Library.addImage(String("forest/rightDoor.png").split("/").join("."), new FLAKIT_ASSET$_480644089);
			Library.addImage(String("forest/ropeBridge.png").split("/").join("."), new FLAKIT_ASSET$_1460216769);
			Library.addImage(String("forest/towerDoor.png").split("/").join("."), new FLAKIT_ASSET$_1213875967);
			Library.addImage(String("forest/decals/pineTree.png").split("/").join("."), new FLAKIT_ASSET$316914079);
			Library.addImage(String("forest/decals/stump.png").split("/").join("."), new FLAKIT_ASSET$_1657714078);
			Library.addImage(String("enemies/archer.png").split("/").join("."), new FLAKIT_ASSET$_1251641895);
			Library.addImage(String("enemies/bear.png").split("/").join("."), new FLAKIT_ASSET$_1811389558);
			Library.addImage(String("enemies/boss.png").split("/").join("."), new FLAKIT_ASSET$_1059533712);
			Library.addImage(String("enemies/demon.png").split("/").join("."), new FLAKIT_ASSET$1903992314);
			Library.addImage(String("enemies/elfMage.png").split("/").join("."), new FLAKIT_ASSET$28606730);
			Library.addImage(String("enemies/fighterDop.png").split("/").join("."), new FLAKIT_ASSET$_1632949578);
			Library.addImage(String("enemies/giant.png").split("/").join("."), new FLAKIT_ASSET$_1579280983);
			Library.addImage(String("enemies/guard.png").split("/").join("."), new FLAKIT_ASSET$_924445735);
			Library.addImage(String("enemies/mageDop.png").split("/").join("."), new FLAKIT_ASSET$201438161);
			Library.addImage(String("enemies/rogueDop.png").split("/").join("."), new FLAKIT_ASSET$478098701);
			Library.addImage(String("enemies/scythe.png").split("/").join("."), new FLAKIT_ASSET$357731548);
			Library.addImage(String("enemies/serpent.png").split("/").join("."), new FLAKIT_ASSET$711283937);
			Library.addImage(String("enemies/skeleton.png").split("/").join("."), new FLAKIT_ASSET$_644484842);
			Library.addImage(String("enemies/skeletonMage.png").split("/").join("."), new FLAKIT_ASSET$_2123834409);
			Library.addImage(String("enemies/spider.png").split("/").join("."), new FLAKIT_ASSET$_2104619363);
			Library.addImage(String("enemies/wolf.png").split("/").join("."), new FLAKIT_ASSET$_1675023862);
			Library.addImage(String("enemies/zombie.png").split("/").join("."), new FLAKIT_ASSET$1235186498);
			Library.addImage(String("enemies/bossDeath/s1.png").split("/").join("."), new FLAKIT_ASSET$101831650);
			Library.addImage(String("enemies/bossDeath/s10.png").split("/").join("."), new FLAKIT_ASSET$_144639212);
			Library.addImage(String("enemies/bossDeath/s11.png").split("/").join("."), new FLAKIT_ASSET$_144639435);
			Library.addImage(String("enemies/bossDeath/s12.png").split("/").join("."), new FLAKIT_ASSET$_144639402);
			Library.addImage(String("enemies/bossDeath/s13.png").split("/").join("."), new FLAKIT_ASSET$_144639385);
			Library.addImage(String("enemies/bossDeath/s14.png").split("/").join("."), new FLAKIT_ASSET$_144639352);
			Library.addImage(String("enemies/bossDeath/s2.png").split("/").join("."), new FLAKIT_ASSET$235721698);
			Library.addImage(String("enemies/bossDeath/s3.png").split("/").join("."), new FLAKIT_ASSET$369611746);
			Library.addImage(String("enemies/bossDeath/s4.png").split("/").join("."), new FLAKIT_ASSET$_1025846302);
			Library.addImage(String("enemies/bossDeath/s5.png").split("/").join("."), new FLAKIT_ASSET$_891956254);
			Library.addImage(String("enemies/bossDeath/s6.png").split("/").join("."), new FLAKIT_ASSET$_758066206);
			Library.addImage(String("enemies/bossDeath/s7.png").split("/").join("."), new FLAKIT_ASSET$_1860447262);
			Library.addImage(String("enemies/bossDeath/s8.png").split("/").join("."), new FLAKIT_ASSET$_1103178782);
			Library.addImage(String("enemies/bossDeath/s9.png").split("/").join("."), new FLAKIT_ASSET$_969288734);
			Library.addImage(String("dungeon/bg.png").split("/").join("."), new FLAKIT_ASSET$_1319924279);
			Library.addImage(String("dungeon/platform.png").split("/").join("."), new FLAKIT_ASSET$_610037691);
			Library.addImage(String("dungeon/decals/cellDoor.png").split("/").join("."), new FLAKIT_ASSET$_642163036);
			Library.addImage(String("dungeon/decals/chandelier.png").split("/").join("."), new FLAKIT_ASSET$_1241710435);
			Library.addImage(String("dungeon/decals/cornerWeb.png").split("/").join("."), new FLAKIT_ASSET$_40946760);
			Library.addImage(String("dungeon/decals/crevice.png").split("/").join("."), new FLAKIT_ASSET$_1618064598);
			Library.addImage(String("dungeon/decals/darkness.png").split("/").join("."), new FLAKIT_ASSET$340311090);
			Library.addImage(String("dungeon/decals/door.png").split("/").join("."), new FLAKIT_ASSET$_689039696);
			Library.addImage(String("dungeon/decals/shield.png").split("/").join("."), new FLAKIT_ASSET$_55392338);
			Library.addImage(String("dungeon/decals/stainedGlass.png").split("/").join("."), new FLAKIT_ASSET$_1055518220);
			Library.addImage(String("dungeon/decals/torch.png").split("/").join("."), new FLAKIT_ASSET$_1005829387);
			Library.addImage(String("dungeon/decals/web1.png").split("/").join("."), new FLAKIT_ASSET$1917177926);
			Library.addImage(String("dungeon/decals/window.png").split("/").join("."), new FLAKIT_ASSET$913944423);
			Library.addImage(String("beach/bg.png").split("/").join("."), new FLAKIT_ASSET$_1016859385);
			Library.addImage(String("beach/bg2.png").split("/").join("."), new FLAKIT_ASSET$_2022735386);
			Library.addImage(String("beach/crate.png").split("/").join("."), new FLAKIT_ASSET$_432456929);
			Library.addImage(String("beach/dynamicDebris.png").split("/").join("."), new FLAKIT_ASSET$_172551549);
			Library.addImage(String("beach/lightningBolt.png").split("/").join("."), new FLAKIT_ASSET$_208024148);
			Library.addImage(String("beach/shipAnimation.png").split("/").join("."), new FLAKIT_ASSET$1524607723);
			Library.addImage(String("beach/towerLightning.png").split("/").join("."), new FLAKIT_ASSET$1413686369);
			Library.addImage(String("beach/waterDebris.png").split("/").join("."), new FLAKIT_ASSET$_1041424489);
			Library.addImage(String("beach/waterDebris2.png").split("/").join("."), new FLAKIT_ASSET$_1921118310);
			Library.addImage(String("balcony/bg.png").split("/").join("."), new FLAKIT_ASSET$_1952964103);
			Library.addImage(String("balcony/distantShip.png").split("/").join("."), new FLAKIT_ASSET$1132726687);
			Library.addImage(String("balcony/platform.png").split("/").join("."), new FLAKIT_ASSET$903879535);
			Library.addSound(String("audio/sfx/beachAmbiance.mp3").split("/").join("."), new FLAKIT_ASSET$_1721183005);
			Library.addSound(String("audio/sfx/bearAttack.mp3").split("/").join("."), new FLAKIT_ASSET$_1048980777);
			Library.addSound(String("audio/sfx/bigDoorOpen.mp3").split("/").join("."), new FLAKIT_ASSET$1013157834);
			Library.addSound(String("audio/sfx/blink.mp3").split("/").join("."), new FLAKIT_ASSET$1568168097);
			Library.addSound(String("audio/sfx/bolt.mp3").split("/").join("."), new FLAKIT_ASSET$898355145);
			Library.addSound(String("audio/sfx/bow.mp3").split("/").join("."), new FLAKIT_ASSET$_1081717828);
			Library.addSound(String("audio/sfx/daggerStab.mp3").split("/").join("."), new FLAKIT_ASSET$2114795605);
			Library.addSound(String("audio/sfx/demon.mp3").split("/").join("."), new FLAKIT_ASSET$_1273588036);
			Library.addSound(String("audio/sfx/demonDie.mp3").split("/").join("."), new FLAKIT_ASSET$_1325507663);
			Library.addSound(String("audio/sfx/fireball.mp3").split("/").join("."), new FLAKIT_ASSET$839206465);
			Library.addSound(String("audio/sfx/frostAttack.mp3").split("/").join("."), new FLAKIT_ASSET$_1377963815);
			Library.addSound(String("audio/sfx/keys.mp3").split("/").join("."), new FLAKIT_ASSET$_714000285);
			Library.addSound(String("audio/sfx/pickup.mp3").split("/").join("."), new FLAKIT_ASSET$_522000301);
			Library.addSound(String("audio/sfx/serpentHiss.mp3").split("/").join("."), new FLAKIT_ASSET$_665961522);
			Library.addSound(String("audio/sfx/skeletonDie.mp3").split("/").join("."), new FLAKIT_ASSET$_1703239848);
			Library.addSound(String("audio/sfx/smallDoorOpen.mp3").split("/").join("."), new FLAKIT_ASSET$_924790506);
			Library.addSound(String("audio/sfx/spiderHiss.mp3").split("/").join("."), new FLAKIT_ASSET$_183583457);
			Library.addSound(String("audio/sfx/startToBeach.mp3").split("/").join("."), new FLAKIT_ASSET$421538717);
			Library.addSound(String("audio/sfx/swordSlash.mp3").split("/").join("."), new FLAKIT_ASSET$_1664806651);
			Library.addSound(String("audio/sfx/throw.mp3").split("/").join("."), new FLAKIT_ASSET$862695400);
			Library.addSound(String("audio/sfx/titleScreenAmbiance.mp3").split("/").join("."), new FLAKIT_ASSET$_1269023392);
			Library.addSound(String("audio/sfx/unlock.mp3").split("/").join("."), new FLAKIT_ASSET$_1381489883);
			Library.addSound(String("audio/sfx/Wisp.mp3").split("/").join("."), new FLAKIT_ASSET$_1864778843);
			Library.addSound(String("audio/sfx/wolfAttack.mp3").split("/").join("."), new FLAKIT_ASSET$526945885);
			Library.addSound(String("audio/sfx/zombieAttack.mp3").split("/").join("."), new FLAKIT_ASSET$133286864);
			Library.addSound(String("audio/sfx/zombieDie.mp3").split("/").join("."), new FLAKIT_ASSET$_300141609);
			Library.addSound(String("audio/music/beach.mp3").split("/").join("."), new FLAKIT_ASSET$1479672229);
			Library.addSound(String("audio/music/boss.mp3").split("/").join("."), new FLAKIT_ASSET$2072822914);
			Library.addSound(String("audio/music/dungeon.mp3").split("/").join("."), new FLAKIT_ASSET$1561877272);
			Library.addSound(String("audio/music/finale.mp3").split("/").join("."), new FLAKIT_ASSET$1847966292);
			Library.addSound(String("audio/music/forest.mp3").split("/").join("."), new FLAKIT_ASSET$_1979622991);
			Library.addSound(String("audio/music/hellther.mp3").split("/").join("."), new FLAKIT_ASSET$_713579553);
			Library.addSound(String("audio/music/tower.mp3").split("/").join("."), new FLAKIT_ASSET$_95992901);
		}
	}
}
